# Generated by Django 5.0.1 on 2024-02-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithText',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_img', models.ImageField(upload_to='captured_images/')),
                ('car_class', models.TextField()),
                ('bunho_img', models.ImageField(upload_to='captured_images/')),
                ('bunho_text', models.TextField()),
                ('bunho_class', models.TextField()),
                ('refuel_amount', models.IntegerField()),
                ('fuel_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('carcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('managercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.businesscode')),
            ],
        ),
    ]
