# Generated by Django 5.0.1 on 2024-02-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCode',
            fields=[
                ('managercode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('gasoline_price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('pump_number', models.IntegerField()),
            ],
        ),
    ]
